import type { NextPage } from "next";
import Head from "next/head";
import { CalendarContainer } from "../components/calendar";

const Home: NextPage = () => {
  return (
    <div className="flex p-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen space-y-2">
        <h1 className="text-xl font-medium">Welcome to Marlonxor Calendar</h1>

        <CalendarContainer />
      </main>
    </div>
  );
};

export default Home;
